# Generated by Django 4.0.5 on 2022-09-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('role', models.CharField(choices=[('responsable informatique', 'Responsable Informatique'), ('chargee affaire', 'Chargee Affaire'), ('responsable logistique1', 'Responsable Logistique 1'), ('responsable financier', 'Responsable Financier'), ('responsable logistique2', 'Responsable Logistique 2')], max_length=100, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralDTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_Dossier', models.IntegerField(null=True)),
                ('fournisseur', models.CharField(max_length=200, null=True)),
                ('pays', models.CharField(max_length=100, null=True)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('client', models.CharField(max_length=200, null=True)),
                ('date_VCL', models.DateTimeField(null=True)),
                ('date_validation_e1', models.DateTimeField(null=True)),
                ('statut_Imp', models.CharField(choices=[('en_negociation', 'En Negociation'), ('confirmee_fourn', 'Confirmee Fourn'), ('ex_c_payement', 'Ex_C_Payement'), ('en_preparation', 'En Preparation'), ('prelevee', 'Prelevee'), ('arrivee_maroc', 'Arrivee Maroc'), ('en_dedouanement', 'En Dedouanement'), ('liquide', 'Liquide'), ('en_entrepot', 'En Entrepot'), ('livree', 'Livree'), ('cloturee', 'Cloturee')], default='None', max_length=20, null=True)),
                ('date_TCS', models.DateTimeField(null=True)),
                ('code_Four_Sage', models.IntegerField(null=True)),
                ('ref_Bon_Cmd_Sage', models.CharField(max_length=200, null=True)),
                ('cat_Cmd', models.CharField(max_length=200, null=True)),
                ('date_CCF', models.DateTimeField(null=True)),
                ('n_FP', models.IntegerField(null=True)),
                ('date_FP', models.DateTimeField(null=True)),
                ('pays_Origine', models.CharField(max_length=200, null=True)),
                ('incoterm', models.CharField(max_length=200, null=True)),
                ('pays_Prt', models.CharField(max_length=200, null=True)),
                ('montant_Dev', models.IntegerField(null=True)),
                ('devise', models.CharField(max_length=200, null=True)),
                ('mode_Pay', models.CharField(max_length=200, null=True)),
                ('delai_Liv', models.CharField(max_length=200, null=True)),
                ('Exec_Co_Pay', models.CharField(max_length=200, null=True)),
                ('date_PPF', models.DateField(null=True)),
                ('date_PAM', models.DateTimeField(null=True)),
                ('date_validation_e2', models.DateTimeField(null=True)),
                ('date_pickup', models.DateTimeField(null=True)),
                ('freightforward', models.CharField(max_length=100, null=True)),
                ('mode_trans', models.CharField(max_length=100, null=True)),
                ('date_AM', models.CharField(max_length=100, null=True)),
                ('transitaire', models.CharField(max_length=100, null=True)),
                ('Mt_ded_dh', models.CharField(max_length=100, null=True)),
                ('date_ld', models.DateTimeField(null=True)),
                ('date_lc', models.DateTimeField(null=True)),
                ('litige', models.CharField(max_length=100, null=True)),
                ('class_litige', models.CharField(max_length=100, null=True)),
                ('date_validation_e3', models.DateTimeField(null=True)),
                ('date_capf', models.DateTimeField(null=True)),
                ('date_capp', models.DateTimeField(null=True)),
                ('date_validation_e4', models.DateTimeField(null=True)),
                ('date_cacrs', models.DateTimeField(null=True)),
                ('date_validation_e5', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
