# Generated by Django 4.0.5 on 2022-08-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rl1',
            name='date_PPF',
            field=models.DateField(),
        ),
    ]
