# Generated by Django 4.0.5 on 2022-08-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_rl1_date_ppf'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcha',
            name='role',
            field=models.TextField(default='chargee affaire'),
        ),
    ]
