# Generated by Django 4.0.5 on 2022-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_base_etape'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldtable',
            name='etape',
            field=models.IntegerField(default=1),
        ),
    ]
