# Generated by Django 4.0.5 on 2022-09-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_generaldtable_options_generaldtable_delai_e2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generaldtable',
            options={},
        ),
    ]
