# Generated by Django 4.0.5 on 2022-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_generaldtable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generaldtable',
            options={'ordering': ['etape']},
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='Exec_Co_Pay',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='Mt_ded_dh',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='cat_Cmd',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='class_litige',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='code_Four_Sage',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_AM',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_CCF',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_FP',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_PAM',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_PPF',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_TCS',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_cacrs',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_capf',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_capp',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_lc',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_ld',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_pickup',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_validation_e2',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_validation_e3',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_validation_e4',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_validation_e5',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='delai_Liv',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='delai_e2',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='delai_e3',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='delai_e4',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='delai_e5',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='devise',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='freightforward',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='incoterm',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='litige',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='mode_Pay',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='mode_trans',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='montant_Dev',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='n_FP',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='pays_Origine',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='pays_Prt',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='ref_Bon_Cmd_Sage',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='statut_Imp',
            field=models.CharField(choices=[('', ''), ('en_negociation', 'En Negociation'), ('confirmee_fourn', 'Confirmee Fourn'), ('ex_c_payement', 'Ex_C_Payement'), ('en_preparation', 'En Preparation'), ('prelevee', 'Prelevee'), ('arrivee_maroc', 'Arrivee Maroc'), ('en_dedouanement', 'En Dedouanement'), ('liquide', 'Liquide'), ('en_entrepot', 'En Entrepot'), ('livree', 'Livree'), ('cloturee', 'Cloturee')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='transitaire',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
