# Generated by Django 4.0.5 on 2022-09-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_generaldtable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldtable',
            name='date_CCF',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_FP',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_PAM',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_PPF',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_TCS',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_cacrs',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_capf',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_capp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_lc',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_ld',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_pickup',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_validation_e2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_validation_e3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_validation_e4',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='date_validation_e5',
            field=models.DateTimeField(null=True),
        ),
    ]
