# Generated by Django 4.0.5 on 2022-09-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_generaldtable_date_ccf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldtable',
            name='code_Four_Sage',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='montant_Dev',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generaldtable',
            name='n_FP',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
