# Generated by Django 4.0.5 on 2022-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_generaldtable_date_vcl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldtable',
            name='date_VCL',
            field=models.DateTimeField(null=True),
        ),
    ]
